sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t unclefredoo2/gregis -f Dockerfile.dev .

script:
  - docker run -e CI=true unclefredoo2/gregis npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-506252780606"
  bucket_path: "docker"
  
on:
  branch: master
travis encrypt --add deploy.access_key_id AKIAXLXYEMQ7DHFYDKET
travis encrypt --add deploy.secret_access_key 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